/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountsIdRouteImport } from './routes/accounts.$id'

const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/accounts/$id': typeof AccountsIdRoute
}
export interface FileRoutesByTo {
  '/accounts/$id': typeof AccountsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/accounts/$id': typeof AccountsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/accounts/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/accounts/$id'
  id: '__root__' | '/accounts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountsIdRoute: typeof AccountsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AccountsIdRoute: AccountsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
